### ISSUE TITLE
Attachment size validation

### ISSUE THREAD

**Issue by penatrix-tc** [topcoder-platform/timeline-wall-api#22]
-
feel free to remove this issue

**Comment by igoroshko** [comment]
Let's set maximum file size to 150Mb for now

**Comment by Dara-K** [comment]
@igoroshko  I tested this and I see it works, thanks! however the content of the window should be different
Instead of "CONFIRMATION" we should have "ERROR"
and the description "File size exceeded limit of 150 MB." should be updated to saty "Your file size exceeds 150MB. Please try again with a smaller file." and this should be in red color #EF476F 
![image](https://user-images.githubusercontent.com/25185079/205273577-85eb5a99-2f63-437c-9995-2d34d18318fa.png)
